"""Each company as its own git repository, across interchangeable providers.

A company folder holds the only things that are genuinely the operator's: the
config, the skills, the notes. Losing them loses the company. Versioning them
per company rather than in the framework repo keeps a private business out of a
public checkout, and lets one company move machines without dragging the others.

Same shape as deploy.py: an ABC, a registry, an order the operator can reorder,
and a local provider that always works with nothing external. The order differs
in one way. deploy.py tries `local` first because publishing to a local web root
is the safe default; here `local` comes last, because an operator who asks for a
company repository almost always means a hosted one, and a bare repo under the
writable home is the fallback that keeps the feature usable offline.

Every hosted repository is created **private**. A company folder can hold
prospect names and correspondence, so public is never a default worth offering.
"""

from __future__ import annotations

import logging
import os
import shutil
from abc import ABC, abstractmethod
from pathlib import Path

import requests

from ..config import cfg
from ..kernel import paths, proc

log = logging.getLogger("corparius.companyrepo")

GIT_TIMEOUT = 180

DEFAULT_IGNORE = """# Runtime state, regenerated by corparius.
data/
state.json
# What a company's own programs print while they run. The source is versioned; the output is not —
# a log that grew on every tick would be a commit on every tick, of a file nobody reads twice.
code/*/app.log
"""


def _git(args: list[str], cwd: str, check: bool = True) -> proc.Completed:
    """Run git in `cwd`. Identity is passed per-invocation rather than written
    into the repo config, so a company repo never disagrees with the operator's
    global git identity."""
    ident = [
        "-c",
        f"user.name={cfg.get('CORP_GIT_AUTHOR_NAME', 'corparius')}",
        "-c",
        f"user.email={cfg.get('CORP_GIT_AUTHOR_EMAIL', 'corparius@localhost')}",
    ]
    out = proc.run(["git", *ident, *args], cwd=cwd, timeout=GIT_TIMEOUT)
    if check and not out.ok:
        raise RuntimeError(out.tail() or f"git {' '.join(args)} failed")
    return out


def git_available() -> bool:
    return bool(shutil.which("git"))


def repo_dir(slug: str) -> str:
    return str(paths.companies_dir() / slug)


def is_repo(slug: str) -> bool:
    return os.path.isdir(os.path.join(repo_dir(slug), ".git"))


def remote_url(slug: str) -> str:
    """The configured `origin`, or "" when there is none."""
    if not is_repo(slug):
        return ""
    out = _git(["remote", "get-url", "origin"], repo_dir(slug), check=False)
    return out.stdout.strip() if out.returncode == 0 else ""


def dirty(slug: str) -> bool:
    """True when the working tree has changes worth committing."""
    if not is_repo(slug):
        return False
    return bool(_git(["status", "--porcelain"], repo_dir(slug)).stdout.strip())


def ensure_repo(slug: str) -> str:
    """Make the company folder a git repository with a first commit. Idempotent:
    an existing repo is left exactly as it is."""
    path = repo_dir(slug)
    if not os.path.isdir(path):
        raise RuntimeError(f"no such company folder: {path}")
    if is_repo(slug):
        return path
    ignore = os.path.join(path, ".gitignore")
    if not os.path.isfile(ignore):
        with open(ignore, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(DEFAULT_IGNORE)
    _git(["init", "-b", "main"], path)
    _git(["add", "."], path)
    _git(["commit", "-q", "-m", f"{slug}: initial company state"], path)
    return path


class RepoProvider(ABC):
    name = "base"

    @abstractmethod
    def available(self) -> bool: ...

    @abstractmethod
    def create(self, slug: str, description: str) -> str:
        """Create (or find) the private remote and return the URL to push to."""


class GitHubProvider(RepoProvider):
    """A private repository on the operator's own GitHub account.

    Creation goes over the API when a token is set, and falls back to the `gh`
    CLI when it is not, so an operator already signed in with `gh` needs to
    store no token at all. The remote is the https URL: pushing then uses the
    credential helper git already has, and no token is ever written into a
    remote URL where `git remote -v` would print it.
    """

    name = "github"
    API = "https://api.github.com"

    def _token(self) -> str:
        return (cfg.get("GITHUB_TOKEN", "") or cfg.get("CORP_GITHUB_TOKEN", "")).strip()

    def available(self) -> bool:
        return bool(self._token()) or bool(shutil.which("gh"))

    def _headers(self) -> dict:
        return {
            "Authorization": f"Bearer {self._token()}",
            "Accept": "application/vnd.github+json",
        }

    def _repo_name(self, slug: str) -> str:
        prefix = cfg.get("CORP_REPO_NAME_PREFIX", "").strip()
        return f"{prefix}{slug}"

    def create(self, slug: str, description: str) -> str:
        name = self._repo_name(slug)
        token = self._token()
        if not token:
            out = proc.run(
                ["gh", "repo", "create", name, "--private", "--description", description],
                timeout=GIT_TIMEOUT,
            )
            if not out.ok and "already exists" not in out.stderr.lower():
                raise RuntimeError(out.tail() or "gh repo create failed")
            who = proc.run(["gh", "api", "user", "--jq", ".login"], timeout=GIT_TIMEOUT)
            login = who.stdout.strip()
            if not login:
                raise RuntimeError("gh is installed but not signed in")
            return f"https://github.com/{login}/{name}.git"

        r = requests.post(
            f"{self.API}/user/repos",
            headers=self._headers(),
            json={"name": name, "private": True, "description": description},
            timeout=30,
        )
        if r.status_code == 422:
            # Already there. Reuse it rather than failing over to another
            # provider, which would scatter one company across two hosts.
            me = requests.get(f"{self.API}/user", headers=self._headers(), timeout=30)
            me.raise_for_status()
            return f"https://github.com/{me.json()['login']}/{name}.git"
        r.raise_for_status()
        repo = r.json()
        if not repo.get("private", False):
            raise RuntimeError("github returned a public repository; refusing to use it")
        return repo["clone_url"]


class GitLabProvider(RepoProvider):
    """A private project on GitLab, self-hosted or gitlab.com. Set GITLAB_TOKEN,
    and CORP_GITLAB_URL when the instance is your own."""

    name = "gitlab"

    def _token(self) -> str:
        return cfg.get("GITLAB_TOKEN", "").strip()

    def _base(self) -> str:
        return cfg.get("CORP_GITLAB_URL", "https://gitlab.com").rstrip("/")

    def available(self) -> bool:
        return bool(self._token())

    def create(self, slug: str, description: str) -> str:
        prefix = cfg.get("CORP_REPO_NAME_PREFIX", "").strip()
        name = f"{prefix}{slug}"
        headers = {"PRIVATE-TOKEN": self._token()}
        r = requests.post(
            f"{self._base()}/api/v4/projects",
            headers=headers,
            json={"name": name, "path": name, "visibility": "private", "description": description},
            timeout=30,
        )
        if r.status_code in (400, 409):
            # "true", not True: requests types query values as str|bytes|int|
            # float, and a dict mixing str with bool widens to dict[str, object],
            # which mypy refuses. GitLab reads the string form identically.
            params: dict[str, str] = {"search": name, "membership": "true"}
            s = requests.get(
                f"{self._base()}/api/v4/projects",
                headers=headers,
                params=params,
                timeout=30,
            )
            s.raise_for_status()
            for proj in s.json():
                if proj.get("path") == name:
                    return proj["http_url_to_repo"]
        r.raise_for_status()
        return r.json()["http_url_to_repo"]


class SSHRemoteProvider(RepoProvider):
    """A bare repository on a box you own, over ssh. Set CORP_REPO_SSH_TARGET to
    a directory, e.g. git@homelab:/srv/git - the slug is appended."""

    name = "ssh"

    def available(self) -> bool:
        return bool(shutil.which("ssh")) and bool(cfg.get("CORP_REPO_SSH_TARGET", "").strip())

    def create(self, slug: str, description: str) -> str:
        target = cfg.get("CORP_REPO_SSH_TARGET", "").strip()
        host, _, base = target.partition(":")
        if not host or not base:
            raise RuntimeError("CORP_REPO_SSH_TARGET must look like user@host:/srv/git")
        path = f"{base.rstrip('/')}/{slug}.git"
        out = proc.run(["ssh", host, f"git init --bare -q {path} && echo ok"], timeout=GIT_TIMEOUT)
        if not out.ok:
            raise RuntimeError(out.tail() or "ssh git init --bare failed")
        return f"{host}:{path}"


class LocalBareProvider(RepoProvider):
    """A bare repository under the writable home. Needs nothing, works offline,
    and survives deleting the company folder by accident. It is the fallback,
    not a backup: it sits on the same disk."""

    name = "local"

    def available(self) -> bool:
        return True

    def create(self, slug: str, description: str) -> str:
        base = cfg.get("CORP_REPO_LOCAL_DIR", "").strip() or str(paths.user_home() / "repos")
        os.makedirs(base, exist_ok=True)
        path = os.path.join(base, f"{slug}.git")
        if not os.path.isdir(path):
            out = proc.run(["git", "init", "--bare", "-q", path], timeout=GIT_TIMEOUT)
            if not out.ok:
                raise RuntimeError(out.tail() or "git init --bare failed")
        return path


REGISTRY: dict[str, RepoProvider] = {
    p.name: p
    for p in [GitHubProvider(), GitLabProvider(), SSHRemoteProvider(), LocalBareProvider()]
}


def _order() -> list[str]:
    raw = cfg.get("CORP_REPO_PROVIDERS", "github,gitlab,ssh,local")
    return [x.strip() for x in raw.split(",") if x.strip()]


def _set_remote(slug: str, url: str) -> None:
    path = repo_dir(slug)
    if remote_url(slug):
        _git(["remote", "set-url", "origin", url], path)
    else:
        _git(["remote", "add", "origin", url], path)


def provision_result(slug: str, description: str = "") -> dict:
    """Create the local repo if needed, then the private remote with the first
    provider that works, and push. Says plainly what happened, the way
    deploy.deploy_result does, so a total failure is never logged as a success.
    """
    if not git_available():
        return {
            "ok": False,
            "provider": "",
            "remote": "",
            "errors": ["git is not on PATH"],
            "skipped": [],
        }
    description = description or f"corparius company: {slug}"
    errors: list[str] = []
    skipped: list[str] = []
    try:
        ensure_repo(slug)
    except Exception as exc:
        return {"ok": False, "provider": "", "remote": "", "errors": [str(exc)], "skipped": []}

    for name in _order():
        provider = REGISTRY.get(name)
        if provider is None:
            skipped.append(f"{name}: unknown provider")
            continue
        if not provider.available():
            skipped.append(f"{name}: not configured")
            continue
        try:
            url = provider.create(slug, description)
            _set_remote(slug, url)
            _git(["push", "-u", "origin", "main"], repo_dir(slug))
            return {
                "ok": True,
                "provider": name,
                "remote": url,
                "errors": errors,
                "skipped": skipped,
            }
        except Exception as exc:  # fall through to the next provider on failure
            errors.append(f"{name}: {exc}")
    return {"ok": False, "provider": "", "remote": "", "errors": errors, "skipped": skipped}


def provision(slug: str, description: str = "") -> str:
    """The human-readable line. A formatter over provision_result."""
    res = provision_result(slug, description)
    if res["ok"]:
        return f"{res['provider']} -> {res['remote']}"
    if res["errors"]:
        return "no provider succeeded (" + "; ".join(res["errors"]) + ")"
    return "no provider available"


def sync(slug: str, message: str) -> dict:
    """Commit the company folder and push when there is anything to commit.

    Never raises: this runs at the end of an autonomous run, and a repository
    that cannot be reached is not a reason to lose the run's result. A failed
    push still leaves the commit locally, so nothing is lost either way.
    """
    if not git_available() or not is_repo(slug):
        return {"ok": False, "committed": False, "pushed": False, "error": "not a repository"}
    try:
        if not dirty(slug):
            return {"ok": True, "committed": False, "pushed": False, "error": ""}
        path = repo_dir(slug)
        _git(["add", "."], path)
        _git(["commit", "-q", "-m", message], path)
    except Exception as exc:
        return {"ok": False, "committed": False, "pushed": False, "error": str(exc)}
    if not remote_url(slug):
        return {"ok": True, "committed": True, "pushed": False, "error": "no remote"}
    path = repo_dir(slug)
    out = _git(["push", "origin", "main"], path, check=False)
    if out.returncode == 0:
        return {"ok": True, "committed": True, "pushed": True, "error": "", "recovered": False}
    reason = (out.stderr or out.stdout).strip()
    # A diverged remote is the one failure worth recovering from without asking: the
    # remote moved, the local moved, and both sides are wanted. Measured on a real
    # install: one commit pushed from elsewhere rejected every automatic push for
    # eight runs, and the repository quietly stopped being a backup.
    if _diverged(reason):
        fixed, note = _rebase_onto_remote(path)
        if fixed:
            again = _git(["push", "origin", "main"], path, check=False)
            if again.returncode == 0:
                return {
                    "ok": True,
                    "committed": True,
                    "pushed": True,
                    "error": "",
                    "recovered": True,
                    # Empty when the rebase was ordinary. When it is not, it names the generated
                    # documents whose remote version was superseded, so a recovery that happened
                    # silently is a recovery the operator can still read about.
                    "note": note,
                }
            reason = (again.stderr or again.stdout).strip()
        else:
            reason = (
                "the remote has commits this copy does not, and rebasing onto them conflicts: "
                f"{note}. Resolve it by hand: git pull --rebase in {path}"
            )
    return {
        "ok": True,
        "committed": True,
        "pushed": False,
        "error": reason[:300],
        "recovered": False,
    }


def _diverged(reason: str) -> bool:
    """Whether a rejected push is the recoverable kind: the remote simply moved."""
    text = (reason or "").lower()
    return "non-fast-forward" in text or "fetch first" in text or "rejected" in text


# The one directory in a company folder whose contents corparius writes and nothing else does.
# `documents.write` puts every agent's output under `<company>/documents/written/`, and
# `documents.save` — the operator dropping a file in — lands in the folder root, "never in
# `written/`", which its own docstring states and a test holds.
#
# That distinction is what makes an automatic conflict resolution defensible at all. Two machines
# that both ran a day produced two end-of-day summaries; picking one is choosing between two things
# corparius wrote. Two versions of `company.yaml`, or of a `site/public` that the operator maintains
# by hand, are two things a *person* wrote, and no rule here is allowed to choose between those.
GENERATED = "documents/written/"


def _conflicting(path) -> list[str]:
    """The paths a rebase stopped on, as git reports them."""
    out = _git(["diff", "--name-only", "--diff-filter=U"], path, check=False)
    return [line.strip() for line in out.stdout.splitlines() if line.strip()]


def _rebase_onto_remote(path) -> tuple[bool, str]:
    """Put the local commits on top of the remote's. Returns (clean, what happened).

    `--autostash` so a run that left the folder dirty does not block its own backup, and an abort on
    any failure: leaving a repository mid-rebase would be worse than the unpushed commits it was
    trying to fix, because the next run would find a detached head and fail unreadably.

    **And a second attempt when every conflict is in corparius's own output.** Measured on a real
    install: the two sides were `vigil: automatic commit after 3 tick(s)` and `after 6 tick(s)`, both
    written by corparius, colliding on `documents/written/end-of-day.md` — the summary the CEO
    rewrites every day. That is corparius conflicting with itself, and telling the operator to open a
    terminal and rebase by hand is asking them to arbitrate between two things they did not write.

    `-X theirs`, and the flag is inverted from what it reads like: during a rebase "ours" is the
    branch being replayed *onto* (the remote) and "theirs" is the commit being replayed (this
    machine's). Measured on a throwaway repository rather than remembered, because getting this
    backwards would silently discard the run that just finished.

    **Nothing is lost.** The remote's commit stays in the history the rebase builds on, so its
    version of the file is one `git show` away — the same "archive, never erase" rule the skill
    curator follows. What is superseded is a generated document, and it is named in the report so
    the operator can go and look at it.
    """
    if _git(["fetch", "origin", "main"], path, check=False).returncode != 0:
        return False, "could not reach the remote"
    out = _git(["rebase", "--autostash", "origin/main"], path, check=False)
    if out.returncode == 0:
        return True, ""

    clashes = _conflicting(path)
    _git(["rebase", "--abort"], path, check=False)
    if not clashes:
        return False, "the rebase failed and reported no conflicting file"
    hand_written = [name for name in clashes if GENERATED not in name.replace("\\", "/")]
    if hand_written:
        # Everything corparius did not write is the operator's, and this is where the terminal is
        # still the honest answer. The files are named now: "resolve it by hand" without saying what
        # is in the way is a request to go and find out.
        return False, "conflicts outside corparius's own output: " + ", ".join(hand_written[:6])

    retry = _git(["rebase", "--autostash", "-X", "theirs", "origin/main"], path, check=False)
    if retry.returncode != 0:
        _git(["rebase", "--abort"], path, check=False)
        return False, "conflicts in generated documents that could not be resolved automatically"
    return True, "superseded on the remote, recoverable in the history: " + ", ".join(clashes[:6])


def ahead_of_remote(slug: str) -> int:
    """How many commits this copy has that the remote does not. 0 when it is level or unknown.

    "Nothing to commit" and "everything is on the remote" are different facts, and conflating them
    is how a publish reports success having pushed nothing: `sync` returns early on a clean tree, so
    a commit made by `ensure_repo` before a remote existed stays local forever while every later call
    says there was nothing to do. Measured exactly that way while wiring `publish_production_code`.
    """
    if not is_repo(slug) or not remote_url(slug):
        return 0
    path = repo_dir(slug)
    mine = _git(["rev-list", "--count", "HEAD"], path, check=False)
    try:
        total = int(mine.stdout.strip())
    except (TypeError, ValueError):
        total = 0
    # **Unknown means everything, not nothing**, and the optimistic reading is what made the first
    # version of this lie. A fetch fails on a remote that has no `main` yet — which is exactly the
    # state of a repository nobody has pushed to — and returning 0 there reported "already on the
    # remote" about a remote holding no files at all. Measured on a throwaway bare repo.
    if _git(["fetch", "origin", "main"], path, check=False).returncode != 0:
        return total
    out = _git(["rev-list", "--count", "origin/main..HEAD"], path, check=False)
    if out.returncode != 0:
        return total
    try:
        return int(out.stdout.strip())
    except (TypeError, ValueError):
        return total


def _ignore_app_logs(slug: str) -> None:
    """Make sure this repository ignores program output, even if it predates the rule.

    `ensure_repo` writes `.gitignore` once and never touches it again, which is right — it is the
    operator's file. But a company versioned before its coder could write programs has no line for
    their logs, and one appended line is the difference between a commit per publish and a commit
    per change.
    """
    path = Path(repo_dir(slug)) / ".gitignore"
    try:
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if "code/*/app.log" in current:
            return
        added = (
            "\n# Program output, added when this company first published code.\ncode/*/app.log\n"
        )
        with open(path, "a", encoding="utf-8", newline="\n") as fh:
            fh.write(added)
        # And out of the index if a publish already put it there. `--ignore-unmatch` because the
        # usual case is that it was never tracked, and that is not an error to report.
        _git(
            ["rm", "--cached", "-q", "--ignore-unmatch", "code/*/app.log"],
            repo_dir(slug),
            check=False,
        )
    except OSError as exc:
        log.info("%s: could not update .gitignore (%s)", slug, exc)


def publish(slug: str, message: str) -> dict:
    """Commit what is new **and** push what is unpushed. Either half may be the one that matters.

    `sync` is the run's end-of-day backup and answers "is there work to bank"; this answers "is this
    company's code somewhere other than this machine", which is a different question with a
    different failure. A folder whose first commit predates its remote is clean, has nothing to
    commit, and is entirely unpublished.
    """
    _ignore_app_logs(slug)
    out = dict(sync(slug, message))
    if out.get("pushed") or not remote_url(slug):
        return out
    behind = ahead_of_remote(slug)
    if behind <= 0:
        return {**out, "ok": True, "pushed": True, "already": True}
    pushed = _git(["push", "origin", "main"], repo_dir(slug), check=False)
    if pushed.returncode == 0:
        return {**out, "ok": True, "pushed": True, "commits": behind}
    return {
        **out,
        "ok": True,
        "pushed": False,
        "error": (pushed.stderr or pushed.stdout).strip()[:300],
    }


def resolve(slug: str, keep: str = "mine") -> dict:
    """Settle a diverged repository, taking one side for the files that clash. Then push.

    The half of the split that is not corparius's to decide. `sync` reconciles conflicts in
    `documents/written/` on its own, because both versions there were written by corparius; a clash
    in `company.yaml` or in a hand-maintained `site/public` is two decisions a *person* made, and
    picking one silently would overwrite a change somebody made from another machine.

    So the decision comes back to the operator — and only the decision. The fetching, the rebasing,
    the strategy flag and the push are this function's job, because a console operator has chosen not
    to use a terminal and a product that sends them to one to finish its own work has handed the
    problem back instead of solving it.

    `keep="mine"` keeps this machine's version of the clashing files, `keep="theirs"` the other
    machine's. Either way both commits stay in the history the rebase builds on, so the version that
    lost is one `git show` away rather than gone.
    """
    # The argument before the world, and the order is not arbitrary. `keep` decides which version of
    # a file survives and it arrives from a browser; checking the repository first would hide a
    # client sending nonsense behind "not a repository" on every company that has none, which is
    # most of them.
    if keep not in ("mine", "theirs"):
        return {"ok": False, "pushed": False, "error": f"unknown choice {keep!r}"}
    if not git_available() or not is_repo(slug) or not remote_url(slug):
        return {"ok": False, "pushed": False, "error": "not a repository with a remote"}
    path = repo_dir(slug)
    if _git(["fetch", "origin", "main"], path, check=False).returncode != 0:
        return {"ok": False, "pushed": False, "error": "could not reach the remote"}
    # Inverted, and measured rather than remembered: during a rebase "ours" is the branch being
    # replayed onto (the remote) and "theirs" is the commit being replayed (this machine's). Reading
    # these the other way round would discard exactly the side the operator asked to keep.
    strategy = "theirs" if keep == "mine" else "ours"
    out = _git(["rebase", "--autostash", "-X", strategy, "origin/main"], path, check=False)
    if out.returncode != 0:
        _git(["rebase", "--abort"], path, check=False)
        return {"ok": False, "pushed": False, "error": (out.stderr or out.stdout).strip()[:300]}
    pushed = _git(["push", "origin", "main"], path, check=False)
    if pushed.returncode != 0:
        return {
            "ok": False,
            "pushed": False,
            "error": (pushed.stderr or pushed.stdout).strip()[:300],
        }
    return {"ok": True, "pushed": True, "error": "", "kept": keep}


def conflicting_paths(slug: str) -> list[str]:
    """Which files a push would collide on, without changing anything.

    Read-only by construction: the rebase is attempted and immediately aborted. The console needs
    this to name the files in the choice it puts in front of the operator, and a choice that said
    "some files conflict" would be a choice made blind.
    """
    if not git_available() or not is_repo(slug) or not remote_url(slug):
        return []
    path = repo_dir(slug)
    if _git(["fetch", "origin", "main"], path, check=False).returncode != 0:
        return []
    out = _git(["rebase", "--autostash", "origin/main"], path, check=False)
    if out.returncode == 0:
        # It applied cleanly, which is a fact worth having found out. Nothing to report and nothing
        # to undo: the copy is simply current now.
        return []
    names = _conflicting(path)
    _git(["rebase", "--abort"], path, check=False)
    return names


def refresh(slug: str) -> dict:
    """Bring the copy up to date **before** a run, not after it.

    This is the fix for the whole class rather than for one occurrence. `sync` only ever pushed, so
    a company whose remote had moved discovered it at the end of a day, with the day's writes already
    committed on top of a stale base — which is precisely when a rebase has two rewritten copies of
    the same generated document to reconcile. Refreshing first means the day is written on top of
    what the remote already had, and the push at the end is an ordinary fast-forward.

    Never raises, and never touches a dirty tree: a run that starts on uncommitted work would have
    that work stashed and replayed by a rebase, and a backup step is not allowed to move an
    operator's files around underneath them. It reports and stands down instead.
    """
    if not git_available() or not is_repo(slug) or not remote_url(slug):
        return {"ok": False, "updated": False, "error": "not a repository with a remote"}
    path = repo_dir(slug)
    if dirty(slug):
        return {"ok": True, "updated": False, "error": "uncommitted changes; left alone"}
    before = _git(["rev-parse", "HEAD"], path, check=False).stdout.strip()
    clean, note = _rebase_onto_remote(path)
    if not clean:
        return {"ok": False, "updated": False, "error": note}
    after = _git(["rev-parse", "HEAD"], path, check=False).stdout.strip()
    return {"ok": True, "updated": before != after, "error": "", "note": note}


def autocommit_enabled() -> bool:
    return cfg.get_bool("CORP_REPO_AUTOCOMMIT", "false")
