"""Export an app as a function deployed beside the site.

The endpoint in appserver.py keeps the key on the operator's machine and every
call inside the budget and the journal. It also means a machine has to be
reachable. For a site that must answer on its own, the function moves to the
host — and what moves with it is the spend: once Netlify holds the key,
corparius cannot see, cap or record a single call.

That is a real trade, not a detail, so the command says it and the generated
file repeats it in a comment at the top. An operator choosing autonomy should
know what they gave up while reading the thing they gave it up for.

Only OpenAI-compatible providers export. `local:` needs Ollama on the host,
`claudecode:` needs the CLI and its login, and neither exists in a serverless
function — refusing is the honest answer, not a config that fails at runtime.
"""

from __future__ import annotations

from pathlib import Path

from . import apps as apps_mod
from .kernel.records import Difficulty
from .llm import OPENAI_COMPAT_PROVIDERS, _split

# Netlify's Node runtime, no dependencies: fetch is built in since Node 18.
TEMPLATE = """// Generated by `corparius apps export netlify`. Edit if you like; it is yours.
//
// WARNING, and it is the whole point of reading this: corparius no longer sees
// these calls. The key lives in this site's environment, so the app's daily
// token ceiling, its rate limit and its entry in the company's cost breakdown
// do not apply here. Whatever this function spends, it spends unobserved.
//
// Set {key_env} in the site's environment variables before deploying.

const SYSTEM = {system};
const MODEL = {model};
const ENDPOINT = {endpoint};
const MAX_TOKENS = {max_tokens};
const ORIGINS = {origins};

function cors(origin) {{
  if (!origin || !ORIGINS.includes(origin)) return null;
  return {{
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Vary": "Origin",
  }};
}}

export default async (request) => {{
  const origin = request.headers.get("origin") || "";
  const headers = cors(origin);
  if (!headers) return new Response("origin not allowed", {{ status: 403 }});
  if (request.method === "OPTIONS") return new Response(null, {{ status: 204, headers }});
  if (request.method !== "POST") return new Response("method not allowed", {{ status: 405 }});

  const key = process.env.{key_env};
  if (!key) return new Response("not configured", {{ status: 503, headers }});

  let input = "";
  try {{
    input = String(((await request.json()) || {{}}).input || "").trim();
  }} catch (e) {{
    input = "";
  }}
  if (!input) return new Response("empty input", {{ status: 400, headers }});

  const upstream = await fetch(ENDPOINT + "/chat/completions", {{
    method: "POST",
    headers: {{ "Content-Type": "application/json", Authorization: "Bearer " + key }},
    body: JSON.stringify({{
      model: MODEL,
      max_tokens: MAX_TOKENS,
      messages: [
        {{ role: "system", content: SYSTEM }},
        {{ role: "user", content: input.slice(0, 4000) }},
      ],
    }}),
  }});
  if (!upstream.ok) return new Response("upstream error", {{ status: 502, headers }});
  const data = await upstream.json();
  const text = ((data.choices || [{{}}])[0].message || {{}}).content || "";
  return new Response(JSON.stringify({{ ok: true, text }}), {{
    status: 200,
    headers: {{ ...headers, "Content-Type": "application/json" }},
  }});
}};

export const config = {{ path: "/api/{name}" }};
"""


class ExportError(Exception):
    """What cannot be exported, and why, in one sentence for the operator."""


def _tier_model(app, settings) -> str:
    return {
        Difficulty.TRIVIAL: settings.trivial_model,
        Difficulty.EASY: settings.normal_model,
        Difficulty.HARD: settings.hard_model,
    }.get(app.tier, settings.normal_model)


def plan(app, settings) -> dict:
    """What the exported function would call, or why it cannot be exported.

    Resolved from the tier the app already declares, so an export runs the same
    model the endpoint would have — until someone edits one of the two.
    """
    target, model = _split(_tier_model(app, settings))
    if target in ("local", "claudecode", "cloud"):
        raise ExportError(
            f"the {app.tier.value} tier points at `{target}:`, which cannot run in a "
            "function: local needs Ollama on the host, claudecode needs the CLI and its "
            "login, and cloud is the Anthropic key you would then be copying out. Point "
            "the tier at an OpenAI-compatible provider, or keep this app on the endpoint."
        )
    spec = OPENAI_COMPAT_PROVIDERS.get(target)
    if not spec or not spec.get("base"):
        raise ExportError(f"unknown provider `{target}` for the {app.tier.value} tier")
    if not app.origins:
        raise ExportError(
            "this app lists no origins, so the exported function would refuse every "
            "browser. Add the site's URL to `origins:` in its YAML first."
        )
    return {
        "provider": target,
        "model": model,
        "endpoint": spec["base"],
        "key_env": str(spec.get("key_env") or ""),
    }


def render(app, target: dict) -> str:
    import json

    return TEMPLATE.format(
        name=app.name,
        system=json.dumps(app.system),
        model=json.dumps(target["model"]),
        endpoint=json.dumps(target["endpoint"]),
        max_tokens=app.max_tokens,
        origins=json.dumps(app.origins),
        key_env=target["key_env"],
    )


def export(slug: str, name: str, out_dir: Path, settings) -> dict:
    """Write netlify/functions/<name>.mjs under out_dir. Refuses to overwrite."""
    app = apps_mod.get(slug, name)
    if app is None:
        raise ExportError(f"no app named '{name}' for company '{slug}'")
    target = plan(app, settings)
    folder = Path(out_dir) / "netlify" / "functions"
    path = folder / f"{app.name}.mjs"
    if path.exists():
        raise ExportError(f"{path} already exists; delete it or export under another name")
    folder.mkdir(parents=True, exist_ok=True)
    path.write_text(render(app, target), encoding="utf-8")
    return {"path": str(path), **target}
