"""Each company as its own git repository, across interchangeable providers.

A company folder holds the only things that are genuinely the operator's: the
config, the skills, the notes. Losing them loses the company. Versioning them
per company rather than in the framework repo keeps a private business out of a
public checkout, and lets one company move machines without dragging the others.

Same shape as deploy.py: an ABC, a registry, an order the operator can reorder,
and a local provider that always works with nothing external. The order differs
in one way. deploy.py tries `local` first because publishing to a local web root
is the safe default; here `local` comes last, because an operator who asks for a
company repository almost always means a hosted one, and a bare repo under the
writable home is the fallback that keeps the feature usable offline.

Every hosted repository is created **private**. A company folder can hold
prospect names and correspondence, so public is never a default worth offering.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from abc import ABC, abstractmethod

import requests

from . import cfg, paths

GIT_TIMEOUT = 180

DEFAULT_IGNORE = """# Runtime state, regenerated by corparius.
data/
state.json
"""


def _git(args: list[str], cwd: str, check: bool = True) -> subprocess.CompletedProcess:
    """Run git in `cwd`. Identity is passed per-invocation rather than written
    into the repo config, so a company repo never disagrees with the operator's
    global git identity."""
    ident = [
        "-c",
        f"user.name={cfg.get('CORP_GIT_AUTHOR_NAME', 'corparius')}",
        "-c",
        f"user.email={cfg.get('CORP_GIT_AUTHOR_EMAIL', 'corparius@localhost')}",
    ]
    out = subprocess.run(
        ["git", *ident, *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=GIT_TIMEOUT,
    )
    if check and out.returncode != 0:
        raise RuntimeError((out.stderr or out.stdout).strip() or f"git {' '.join(args)} failed")
    return out


def git_available() -> bool:
    return bool(shutil.which("git"))


def repo_dir(slug: str) -> str:
    return str(paths.companies_dir() / slug)


def is_repo(slug: str) -> bool:
    return os.path.isdir(os.path.join(repo_dir(slug), ".git"))


def remote_url(slug: str) -> str:
    """The configured `origin`, or "" when there is none."""
    if not is_repo(slug):
        return ""
    out = _git(["remote", "get-url", "origin"], repo_dir(slug), check=False)
    return out.stdout.strip() if out.returncode == 0 else ""


def dirty(slug: str) -> bool:
    """True when the working tree has changes worth committing."""
    if not is_repo(slug):
        return False
    return bool(_git(["status", "--porcelain"], repo_dir(slug)).stdout.strip())


def ensure_repo(slug: str) -> str:
    """Make the company folder a git repository with a first commit. Idempotent:
    an existing repo is left exactly as it is."""
    path = repo_dir(slug)
    if not os.path.isdir(path):
        raise RuntimeError(f"no such company folder: {path}")
    if is_repo(slug):
        return path
    ignore = os.path.join(path, ".gitignore")
    if not os.path.isfile(ignore):
        with open(ignore, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(DEFAULT_IGNORE)
    _git(["init", "-b", "main"], path)
    _git(["add", "."], path)
    _git(["commit", "-q", "-m", f"{slug}: initial company state"], path)
    return path


class RepoProvider(ABC):
    name = "base"

    @abstractmethod
    def available(self) -> bool: ...

    @abstractmethod
    def create(self, slug: str, description: str) -> str:
        """Create (or find) the private remote and return the URL to push to."""


class GitHubProvider(RepoProvider):
    """A private repository on the operator's own GitHub account.

    Creation goes over the API when a token is set, and falls back to the `gh`
    CLI when it is not, so an operator already signed in with `gh` needs to
    store no token at all. The remote is the https URL: pushing then uses the
    credential helper git already has, and no token is ever written into a
    remote URL where `git remote -v` would print it.
    """

    name = "github"
    API = "https://api.github.com"

    def _token(self) -> str:
        return (cfg.get("GITHUB_TOKEN", "") or cfg.get("CORP_GITHUB_TOKEN", "")).strip()

    def available(self) -> bool:
        return bool(self._token()) or bool(shutil.which("gh"))

    def _headers(self) -> dict:
        return {
            "Authorization": f"Bearer {self._token()}",
            "Accept": "application/vnd.github+json",
        }

    def _repo_name(self, slug: str) -> str:
        prefix = cfg.get("CORP_REPO_NAME_PREFIX", "").strip()
        return f"{prefix}{slug}"

    def create(self, slug: str, description: str) -> str:
        name = self._repo_name(slug)
        token = self._token()
        if not token:
            out = subprocess.run(
                ["gh", "repo", "create", name, "--private", "--description", description],
                capture_output=True,
                text=True,
                timeout=GIT_TIMEOUT,
            )
            if out.returncode != 0 and "already exists" not in (out.stderr or "").lower():
                raise RuntimeError((out.stderr or out.stdout).strip() or "gh repo create failed")
            who = subprocess.run(
                ["gh", "api", "user", "--jq", ".login"],
                capture_output=True,
                text=True,
                timeout=GIT_TIMEOUT,
            )
            login = who.stdout.strip()
            if not login:
                raise RuntimeError("gh is installed but not signed in")
            return f"https://github.com/{login}/{name}.git"

        r = requests.post(
            f"{self.API}/user/repos",
            headers=self._headers(),
            json={"name": name, "private": True, "description": description},
            timeout=30,
        )
        if r.status_code == 422:
            # Already there. Reuse it rather than failing over to another
            # provider, which would scatter one company across two hosts.
            me = requests.get(f"{self.API}/user", headers=self._headers(), timeout=30)
            me.raise_for_status()
            return f"https://github.com/{me.json()['login']}/{name}.git"
        r.raise_for_status()
        repo = r.json()
        if not repo.get("private", False):
            raise RuntimeError("github returned a public repository; refusing to use it")
        return repo["clone_url"]


class GitLabProvider(RepoProvider):
    """A private project on GitLab, self-hosted or gitlab.com. Set GITLAB_TOKEN,
    and CORP_GITLAB_URL when the instance is your own."""

    name = "gitlab"

    def _token(self) -> str:
        return cfg.get("GITLAB_TOKEN", "").strip()

    def _base(self) -> str:
        return cfg.get("CORP_GITLAB_URL", "https://gitlab.com").rstrip("/")

    def available(self) -> bool:
        return bool(self._token())

    def create(self, slug: str, description: str) -> str:
        prefix = cfg.get("CORP_REPO_NAME_PREFIX", "").strip()
        name = f"{prefix}{slug}"
        headers = {"PRIVATE-TOKEN": self._token()}
        r = requests.post(
            f"{self._base()}/api/v4/projects",
            headers=headers,
            json={"name": name, "path": name, "visibility": "private", "description": description},
            timeout=30,
        )
        if r.status_code in (400, 409):
            # "true", not True: requests types query values as str|bytes|int|
            # float, and a dict mixing str with bool widens to dict[str, object],
            # which mypy refuses. GitLab reads the string form identically.
            params: dict[str, str] = {"search": name, "membership": "true"}
            s = requests.get(
                f"{self._base()}/api/v4/projects",
                headers=headers,
                params=params,
                timeout=30,
            )
            s.raise_for_status()
            for proj in s.json():
                if proj.get("path") == name:
                    return proj["http_url_to_repo"]
        r.raise_for_status()
        return r.json()["http_url_to_repo"]


class SSHRemoteProvider(RepoProvider):
    """A bare repository on a box you own, over ssh. Set CORP_REPO_SSH_TARGET to
    a directory, e.g. git@homelab:/srv/git - the slug is appended."""

    name = "ssh"

    def available(self) -> bool:
        return bool(shutil.which("ssh")) and bool(cfg.get("CORP_REPO_SSH_TARGET", "").strip())

    def create(self, slug: str, description: str) -> str:
        target = cfg.get("CORP_REPO_SSH_TARGET", "").strip()
        host, _, base = target.partition(":")
        if not host or not base:
            raise RuntimeError("CORP_REPO_SSH_TARGET must look like user@host:/srv/git")
        path = f"{base.rstrip('/')}/{slug}.git"
        out = subprocess.run(
            ["ssh", host, f"git init --bare -q {path} && echo ok"],
            capture_output=True,
            text=True,
            timeout=GIT_TIMEOUT,
        )
        if out.returncode != 0:
            raise RuntimeError(out.stderr.strip() or "ssh git init --bare failed")
        return f"{host}:{path}"


class LocalBareProvider(RepoProvider):
    """A bare repository under the writable home. Needs nothing, works offline,
    and survives deleting the company folder by accident. It is the fallback,
    not a backup: it sits on the same disk."""

    name = "local"

    def available(self) -> bool:
        return True

    def create(self, slug: str, description: str) -> str:
        base = cfg.get("CORP_REPO_LOCAL_DIR", "").strip() or str(paths.user_home() / "repos")
        os.makedirs(base, exist_ok=True)
        path = os.path.join(base, f"{slug}.git")
        if not os.path.isdir(path):
            out = subprocess.run(
                ["git", "init", "--bare", "-q", path],
                capture_output=True,
                text=True,
                timeout=GIT_TIMEOUT,
            )
            if out.returncode != 0:
                raise RuntimeError(out.stderr.strip() or "git init --bare failed")
        return path


REGISTRY: dict[str, RepoProvider] = {
    p.name: p
    for p in [GitHubProvider(), GitLabProvider(), SSHRemoteProvider(), LocalBareProvider()]
}


def _order() -> list[str]:
    raw = cfg.get("CORP_REPO_PROVIDERS", "github,gitlab,ssh,local")
    return [x.strip() for x in raw.split(",") if x.strip()]


def _set_remote(slug: str, url: str) -> None:
    path = repo_dir(slug)
    if remote_url(slug):
        _git(["remote", "set-url", "origin", url], path)
    else:
        _git(["remote", "add", "origin", url], path)


def provision_result(slug: str, description: str = "") -> dict:
    """Create the local repo if needed, then the private remote with the first
    provider that works, and push. Says plainly what happened, the way
    deploy.deploy_result does, so a total failure is never logged as a success.
    """
    if not git_available():
        return {
            "ok": False,
            "provider": "",
            "remote": "",
            "errors": ["git is not on PATH"],
            "skipped": [],
        }
    description = description or f"corparius company: {slug}"
    errors: list[str] = []
    skipped: list[str] = []
    try:
        ensure_repo(slug)
    except Exception as exc:
        return {"ok": False, "provider": "", "remote": "", "errors": [str(exc)], "skipped": []}

    for name in _order():
        provider = REGISTRY.get(name)
        if provider is None:
            skipped.append(f"{name}: unknown provider")
            continue
        if not provider.available():
            skipped.append(f"{name}: not configured")
            continue
        try:
            url = provider.create(slug, description)
            _set_remote(slug, url)
            _git(["push", "-u", "origin", "main"], repo_dir(slug))
            return {
                "ok": True,
                "provider": name,
                "remote": url,
                "errors": errors,
                "skipped": skipped,
            }
        except Exception as exc:  # fall through to the next provider on failure
            errors.append(f"{name}: {exc}")
    return {"ok": False, "provider": "", "remote": "", "errors": errors, "skipped": skipped}


def provision(slug: str, description: str = "") -> str:
    """The human-readable line. A formatter over provision_result."""
    res = provision_result(slug, description)
    if res["ok"]:
        return f"{res['provider']} -> {res['remote']}"
    if res["errors"]:
        return "no provider succeeded (" + "; ".join(res["errors"]) + ")"
    return "no provider available"


def sync(slug: str, message: str) -> dict:
    """Commit the company folder and push when there is anything to commit.

    Never raises: this runs at the end of an autonomous run, and a repository
    that cannot be reached is not a reason to lose the run's result. A failed
    push still leaves the commit locally, so nothing is lost either way.
    """
    if not git_available() or not is_repo(slug):
        return {"ok": False, "committed": False, "pushed": False, "error": "not a repository"}
    try:
        if not dirty(slug):
            return {"ok": True, "committed": False, "pushed": False, "error": ""}
        path = repo_dir(slug)
        _git(["add", "."], path)
        _git(["commit", "-q", "-m", message], path)
    except Exception as exc:
        return {"ok": False, "committed": False, "pushed": False, "error": str(exc)}
    if not remote_url(slug):
        return {"ok": True, "committed": True, "pushed": False, "error": "no remote"}
    out = _git(["push", "origin", "main"], repo_dir(slug), check=False)
    if out.returncode != 0:
        return {
            "ok": True,
            "committed": True,
            "pushed": False,
            "error": (out.stderr or out.stdout).strip()[:200],
        }
    return {"ok": True, "committed": True, "pushed": True, "error": ""}


def autocommit_enabled() -> bool:
    return cfg.get_bool("CORP_REPO_AUTOCOMMIT", "false")
