"""Minting and checking a device credential. Rank 0, stdlib only.

A paired device presents `corp_<id>.<secret>`. The id is **not** secret and is there so a
verification costs one indexed lookup instead of a scan: without it, checking a credential would
mean hashing it once per stored client, and the cost of a wrong guess would grow with the number
of devices an operator has paired.

## Why SHA-256 and not scrypt

The plan said scrypt, "the primitive `secretbox` already uses". Measured on this machine before
choosing:

```text
scrypt n=2**14 r=8 p=1   87.1 ms   ~16 MiB per call
scrypt n=2**12           21.3 ms
sha256                   0.0014 ms
```

A memory-hard KDF exists to make **low-entropy guesses** expensive. There are no guesses to make
expensive here: `secret` is `secrets.token_urlsafe(32)` — 256 bits — and it is generated by this
module and **never accepted from a caller**, which is what guarantees that. Against an attacker
holding the store file, SHA-256 of 256 random bits and scrypt of 256 random bits are both a
2^256 search; scrypt buys nothing.

What it would cost is real. This check runs on every authenticated request of a polled API, and
an *unauthenticated* caller sending a bogus credential would force 87 ms and 16 MiB of
allocation per attempt — a denial-of-service lever handed out for free, in a server whose whole
threat model is that it is reachable.

`secretbox` keeps scrypt and should: there the input is an operator's passphrase, which is
exactly the low-entropy case a KDF is for. Same primitive, different question. See ADR 0009.

The salt is per client and stored beside the hash. It is not defending entropy — there is
nothing to precompute against 256 random bits — it is there so two devices that somehow shared a
secret would still not share a row, and so the column cannot be used as an equality oracle
between installations.
"""

from __future__ import annotations

import hashlib
import hmac
import secrets

# A recognisable start, so a leaked string can be identified for what it is — by a secret
# scanner, or by an operator finding it in a config file they are about to commit.
PREFIX = "corp_"
_SEP = "."

# 256 bits. The number the paragraph above depends on, so it is a constant rather than a literal
# buried in a call: lowering it would silently invalidate the reasoning for SHA-256.
SECRET_BYTES = 32


def mint() -> tuple[str, str, str]:
    """A new credential: `(id, secret, presented)`.

    Three values because the three go to three places — the id and a hash of the secret into the
    store, the whole presented string to the operator once and never again.
    """
    client_id = secrets.token_hex(8)
    secret = secrets.token_urlsafe(SECRET_BYTES)
    return client_id, secret, f"{PREFIX}{client_id}{_SEP}{secret}"


def split(presented: str) -> tuple[str, str]:
    """`(id, secret)` from what a client sent, or `("", "")` if it is not one of ours.

    Deliberately total: a malformed credential is not an exception, it is a failed
    authentication, and the caller has one branch for both.
    """
    value = (presented or "").strip()
    if not value.startswith(PREFIX) or _SEP not in value:
        return "", ""
    client_id, _, secret = value[len(PREFIX) :].partition(_SEP)
    if not client_id or not secret:
        return "", ""
    return client_id, secret


def new_salt() -> str:
    return secrets.token_hex(16)


def hash_secret(secret: str, salt: str) -> str:
    return hashlib.sha256(f"{salt}{secret}".encode()).hexdigest()


def verify(secret: str, salt: str, expected: str) -> bool:
    """`compare_digest`, not `==`.

    Both are hex digests of the same length here, so the timing signal is small — but "small"
    is an argument that stops being true when someone changes the shape of one side, and this is
    the line where that would matter.
    """
    return hmac.compare_digest(hash_secret(secret, salt), expected or "")
